import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavbarWithSearch from "@/components/shared/NavbarWithSearch";

const inter = Inter({ subsets: ["latin"] });



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={`${inter.className} bg-slate-950 text-white`}>
        <NavbarWithSearch />
        {children}
      </body>
    </html>
  );
}
